### ISSUE TITLE
System76 Roadmap is now 2 years out of date

### ISSUE THREAD

**Issue by gene1wood** [system76/docs#1150]
[The System76 Roadmap](https://github.com/system76/docs/blob/master/content/roadmap.md) appears to have been abandoned. The Roadmap was written [sometime before April 2020](https://github.com/system76/docs/pull/330/commits/1b10b100801a3cf0103d96c3c118b609b5e88998#diff-7ba0b6c6ad1d6ca2a2ad35515ef16a0f992fe51d58bb7519452e15f7a1454237) (The https://github.com/pop-os/docs repo mentioned in that PR appears have been overwritten with a new repo in [March 2022](https://github.com/pop-os/docs/commit/ebbd8bd933e032a0d3579c2a11164b7325fb1e6f) so I can't see the git history before April 2020. Here's the page [at the end of 2019](https://web.archive.org/web/20191225083332/http://pop.system76.com/docs/roadmap/)). Since April 2020 it has only had formatting changes.

What is the current System76 Roadmap? I imagine it has changed as the existing roadmap comes from before Pop!_OS 22.04 came out and doesn't mention 22.04.

**Comment by jacobgkau** [comment]
On the software side, the current roadmap is based largely around finishing [COSMIC Epoch](https://github.com/pop-os/cosmic-epoch). After that, an immutable version of Pop!_OS may be considered, but it's currently still in the exploratory stages. (This article was specifically titled `for Pop!_OS`, so it wouldn't include hardware System76 projects such as the Virgo laptop or firmware items.)

A number of the currently-planned features in this article have already been completed (e.g. the async fetcher, Pop!_Shell, the support utility, upgrading the Recovery partition in Pop!_Upgrade, etc.) Others that are GNOME-specific are probably not going to happen anymore since work has moved to COSMIC Epoch.

We might want to just remove this article for the time being since it's not being updated. It's just another place we'd have to update every time we release updates elsewhere, and features we want to announce or highlight are typically covered on the [blog](https://blog.system76.com/).

**Comment by gene1wood** [comment]
@ahoneybun Jacob's suggestion was to remove [the article](https://github.com/system76/docs/blob/master/content/roadmap.md), however it looks like it's still up on the site

https://support.system76.com/articles/roadmap/

**Comment by ahoneybun** [comment]
@gene1wood I'll move it with this PR to the archived folder:

https://github.com/system76/docs/pull/1157
