### ISSUE TITLE
Add ~.bashrc commands to Tensorflow-cuda install instructions 

### ISSUE THREAD

**Issue by dbuscombe-usgs** [system76/docs#126]
I don't think the ![tensorflow install instructions](https://support.system76.com/articles/install-tensorflow/) are complete. In order to link my python 3.6 with the ```tensorflow-cuda-latest``` (which, at the time of writing, installs tensorflow 1.11 and cuda-10.0) I had to add the following lines to ~/.bashrc 

```
export PATH=/usr/lib/tensorflow1.11-cuda10.0:/usr/lib/cuda-10.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/lib/cuda-10.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export PYTHONPATH=/usr/lib/tensorflow1.11-cuda10.0/lib/python3.6:$PYTHONPATH
```

**Comment by ahoneybun** [comment]
TensorFlow is split into two articles, one for installing it and one for using it. You can find the article that goes over using it here:

https://support.system76.com/articles/use-tensorflow/

**Comment by mmstick** [comment]
@dbuscombe-usgs You do have to restart in order for the new lib directories to be included in the paths. The correct paths are actually `/usr/lib/tensorflow` and `/usr/lib/cuda`, since these are symbolically linked to the active toolchain set by `update-alternatives`.

Only the `PYTHONPATH` is truly required (only when using the Python bindings), but it shouldn't be part of your session's `PYTHONPATH` since it includes some Python dependencies that potentially may break other Python packages in the system.

**Comment by dbuscombe-usgs** [comment]
@mmstick Thanks for reopening with that useful info. Might be a good idea to add the 'reboot' advice on the website. Some advice on how to install tensorflow-gpu within conda environments would also be great. Thanks!

**Comment by dbuscombe-usgs** [comment]
On a fresh install of pop!OS, I noticed that setting the ```PYTHONPATH``` is required in ~/.bashrc, like so 

```
PYTHONPATH=/usr/lib/tensorflow1.11-cuda10.0/lib/python3.6
```

**Comment by mmstick** [comment]
I'd recommend setting it per project rather than system-wide. Never know if one of its Python libs may alter behavior / break system Python libs.
