### ISSUE TITLE
Pop OS! Installer cannot see an eMMC drive

### ISSUE THREAD

**Issue by dieterzakel** [system76/docs#522]
Ladies and Gentlemen:
I have a Lenovo Idea1 11ADA05 Laptop with Windows on it.
This laptop has an eMMC drive.
The installer cannot see the drive so I cannot partition it.
What is the issue here?
Thank you very much!

**Comment by jacobgkau** [comment]
Welcome! This repository is for the System76/Pop!_OS support article website: https://support.system76.com/ 

General issues should be opened in the Pop!_OS repository here: https://github.com/pop-os/pop 

I tried to transfer this issue for you, but I can't transfer it since these two repositories are in different organizations. I'm closing the issue here; please re-open it in the correct repository (https://github.com/pop-os/pop if you're not sure.)

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by dieterzakel** [comment]
Thank you very much! 

—
Kind regards
Dieter Zakel
