### ISSUE TITLE
Error while loggin in pop os 

### ISSUE THREAD

**Issue by kharevkk** [system76/docs#619]
I am getting an error after logging that something is wrong and try again after log out. Pic attached.  I have tried fsck check as well. Seems okay.
![20210527_181621](https://user-images.githubusercontent.com/71775770/119828707-11948b00-bf18-11eb-985b-c30fbcd25f31.jpg)

Help!

**Comment by jacobgkau** [comment]
@kharevkk I'm sorry about the login trouble! This repository is for the documentation at [support.system76.com](https://support.system76.com/).

If you're a System76 customer, please open a support ticket through that website so our support team can take a look. Otherwise, the correct location for Pop!_OS issues is the Pop!_OS repository: https://github.com/pop-os/pop
