### ISSUE TITLE
Pop!_OS 20.04: DisplayLink displays are black - please cherry-pick xserver patch

### ISSUE THREAD

**Issue by lspintzyk** [system76/docs#643]
Hi
This was raised on DisplayLink evdi issue tracker:
https://github.com/DisplayLink/evdi/issues/279

We have found that problem is inside XServer that is failing to lightup display after Mesa upgrade.
We have fixed that in XServer, now it is required to cherry-pick that fix into your repos so that your users can benefit from that.

XServer issue link: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1183
Merged in fix to stable server-1.20-branch: https://gitlab.freedesktop.org/xorg/xserver/-/merge_requests/683

**Comment by jacobgkau** [comment]
@lspintzyk Thank you for opening an issue! This repository is for the System76/Pop!_OS documentation website, https://support.system76.com/. There is no DisplayLink or X code in this repository.

For general issues with Pop!_OS, the correct repository to use is https://github.com/pop-os/pop. I would also advise that Pop!_OS does not currently fork/modify any xserver packages, we currently use the upstream packages from Ubuntu. I see that there's already a Launchpad bug open to get this fixed in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/1931547 

I'm closing this issue since it is not an issue with the documentation website (and I cannot transfer across GitHub organizations to the correct Pop!_OS repository.) If you feel this needs to be tracked on the Pop!_OS side (which would be fair, since we are shipping a newer kernel that exposes this xserver issue), you are welcome to open an issue in the [general Pop!_OS repository](https://github.com/pop-os/pop) or the [Pop!_OS kernel repository](https://github.com/pop-os/linux/).
