### ISSUE TITLE
Gnome/COSMIC 'resets' after screen timeout

### ISSUE THREAD

**Issue by shiftlessbadger** [system76/docs#734]
Hello,
I am running a AMD Ryzen 7 2700X + NVIDIA GT GTX 1030, pop os 21.04. After my screen times out and goes blank, when I reawaken it by mouse or keyboard, it comes back with gnome reconfigured (I think): all widgets/applets that normally run in the top status bar disappear, tiling is turned off, all work spaces disappear, the dock disappears, and command key behaviour returns to 20.04 (ie it pulls up the old interface with small windows of open programs instead of the list function that is new with COSMIC). What's going on here?

**Comment by jacobgkau** [comment]
Thank you for the report. This repository is for the support documentation at https://support.system76.com. For general issues with Pop!_OS, please use the Pop!_OS repository here: https://github.com/pop-os/pop 

I cannot transfer this issue to the correct repository because I cannot transfer between organizations, so I'm closing it.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).
