### ISSUE TITLE
Can't boot from USB with Windows 10

### ISSUE THREAD

**Issue by MickAmest** [system76/docs#751]
Hello everyone!

I'm trying to install Windows 10 alongside with Pop OS 21.04. I already have Pop OS installed, created the partition in which Windows will be installed and made the bootable USB with Windows 10, following the instructions on the documents here. However, when I turn my computer off, plug the USB and try to boot from the USB, it kind of does not detect it. It does not show as an option to boot from in the boot menu. I tried creating the bootable USB both using WoeUS and creating another one on Windows (in another machine) but neither works. In both cases I can see all the files and directories in the USB, as you can see in the image.

![Captura de pantalla de 2021-08-15 08-35-08](https://user-images.githubusercontent.com/59746966/129480395-dfc8cfea-c904-47c0-a7da-4820e4bdea8c.png)

Does anyone know what could the problem or how could I fix it?

Thank you in advance"

**Comment by storyaddict** [comment]
Hi @MickAmest,

Thanks for reaching out! However, this is not the correct place for this Issue report.

If you have System76 hardware, the best place to troubleshoot this would be on a support ticket.

If you don't have System76 hardware we have community members and devs who may be able to help with your issue here: 
https://chat.pop-os.org/ 

From your description, it sounds like you may need to try a different USB, or Windows ISO.

Best,

Nathaniel
