### ISSUE TITLE
Dash to Dock on Pop!_OS article

### ISSUE THREAD

**Issue by nibble0101** [system76/docs#950]
There is a [great article](https://support.system76.com/articles/dash-to-dock/) on how to install the [dash to dock](https://micheleg.github.io/dash-to-dock/) extension. However, the article doesn't explain how one may uninstall it. I installed the extension but didn't like it that much and I want to remove it all together but I ave no idea how.

It would be great to include a section on how one can uninstall it.

**Comment by garnerlogan65** [comment]
To be honest, the article needs a big change. https://github.com/system76/docs/issues/940 -- it isn't as useful now since there's a built in dock on Pop for a while now. I'm not sure which direction we're going to go with it, but I'm not sure an uninstall section wil be added. You should be able to open the Extensions app and remove it.

**Comment by garnerlogan65** [comment]
The article is being updated to reflect up-to-date information, will consider adding a section on removal.
